### ISSUE TITLE
Can't run because no spec files were found.

### ISSUE THREAD

**Issue by jc61990** [emma-k-alexandra/Laundry-IDs#2]
jc@JC-DESKTOP:~/Laundry-IDs$ cat output/csc_service_works_1_to_1001.log
Can't run because no spec files were found.

We searched for specs matching this glob pattern:

  > /home/jc/Laundry-IDs/cypress/integration/csc.service.works.spec.js

There is no integration folder under cypress

**Comment by emma-k-alexandra** [comment]
Thanks for letting me know, looks like I failed to update the cypress "test" locations when upgrading. Just fixed it.
